modLoader = "javafml"
loaderVersion = "[${forge_version},)"
#issueTrackerURL = ""
license = "GPL-3.0"
[[mods]]
modId = "createtraintickets"
version = "${version}"
displayName = "Create: Train Tickets"
authors = "TheAmazingLucas"
description = '''
This is an example description! Tell everyone what your mod is about!
'''
logoFile = "icon.png"

[[dependencies.createtraintickets]]
modId = "forge"
mandatory = true
versionRange = "[${forge_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.createtraintickets]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version}"
ordering = "NONE"
side = "BOTH"

[[dependencies.createtraintickets]]
modId="create"
mandatory=true
versionRange="${create_version}"
ordering="NONE"
side="BOTH"